# Site settings
title: The Distributed Computing Lab (DCLab)
email: dclab-skku@gmail.com
description: > # This means to ignore newlines until "baseurl:"
   The website for the research group of Dr. Young Ik Eom at the University
   of SKK in the Department of Electrical & Computer Engineering
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://dclab-skku.github.io" # the base hostname & protocol for your site
twitter_username: dclab4u
github_username:  dclab4u
array: []

# Build settings
markdown: kramdown

collections:
  project:
    output: true
  members:
    output: true
  papers:
    output: true
  gallery:
    output: true
  research_area:
    output: true
  misc:
    output: true

plugins:
  - jekyll-sitemap
